version: "3.8"

services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app

    depends_on:
      - db
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=devdb
      - DB_USER=devuser
      - DB_PASSWORD=beyzo

  db:
    container_name: todo_db
    image: postgres:13
    restart: always
    #volumes:
     # - dev-db-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=devdb
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=beyzo
  #volumes:
      #dev-db-data:
    ports:
      - "5437:5432"
