# Generated by Django 4.1.2 on 2022-11-10 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_project',
        ),
        migrations.AddField(
            model_name='user',
            name='current_project',
            field=models.ManyToManyField(to='core.project'),
        ),
    ]
