# Generated by Django 4.1.2 on 2022-11-02 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=257, unique=True)),
                ('code', models.IntegerField()),
                ('description', models.TextField()),
                ('active_issue_count', models.IntegerField(default=0)),
                ('solved_issue_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField()),
                ('start_date', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='active_work_project_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_worked_project',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='current_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_project', to='core.project'),
        ),
    ]
