# Generated by Django 4.1.2 on 2022-11-10 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_user_current_project_user_current_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_project',
            field=models.ManyToManyField(related_query_name='projects', to='core.project'),
        ),
    ]
