# Generated by Django 4.1.2 on 2022-11-02 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_project_id_alter_project_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='current_project',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
