# Generated by Django 4.1.2 on 2022-11-02 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_user_current_project_delete_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=257, unique=True)),
                ('description', models.TextField()),
                ('active_issue_count', models.IntegerField(default=0)),
                ('solved_issue_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField()),
                ('start_date', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='current_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_project', to='core.project'),
        ),
    ]
