# Generated by Django 4.1.2 on 2022-11-11 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_user_current_project_user_project_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=257, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField()),
                ('opened_by', models.CharField(max_length=257)),
                ('assigned_by', models.CharField(max_length=257, null=True)),
                ('assigned_to', models.CharField(max_length=257, null=True)),
                ('assignment_date', models.DateTimeField()),
                ('created_at', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
                ('related_issues', models.TextField()),
            ],
        ),
    ]
