# Generated by Django 4.1.2 on 2022-11-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_beyzo_alter_project_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=257, unique=True)),
                ('description', models.TextField()),
                ('active_issue_count', models.IntegerField(default=0)),
                ('solved_issue_count', models.IntegerField(default=0)),
                ('is_active', models.BooleanField()),
                ('start_date', models.DateTimeField()),
                ('deadline', models.DateTimeField()),
            ],
        ),
    ]
