# Generated by Django 4.1.2 on 2022-11-05 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_projects'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Beyzo',
        ),
        migrations.AlterField(
            model_name='projects',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
