# Generated by Django 4.1.2 on 2022-11-12 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_issue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='assignment_date',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='issue',
            name='deadline',
            field=models.DateTimeField(null=True),
        ),
    ]
