# Generated by Django 4.1.2 on 2022-11-06 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_delete_beyzo_alter_projects_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='active_issue_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='projects',
            name='solved_issue_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
