# Generated by Django 4.1.2 on 2022-11-12 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_issue_assignment_date_alter_issue_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='related_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.project'),
        ),
    ]
