# Generated by Django 4.1.2 on 2022-11-06 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_projects_active_issue_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='current_project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='current_project', to='core.projects'),
        ),
    ]
